version: '3.3'
services:
    eclipse-mosquitto:
        ports:
            - '1883:1883'
            - '9001:9001'
        volumes:
            - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
        image: eclipse-mosquitto
        restart: unless-stopped
